version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - HF_API_KEY=${HF_API_KEY}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - DEPLOY_ENV=azure  
    volumes:
      - ./app:/app
      - ./data:/app/data
